/**
 * Dedicated Engine using youtube-transcript package with robust fallbacks
 */
import { YoutubeTranscript } from "youtube-transcript";
import { formatTimestamp, decodeEntities, type TranscriptResponse, type TranscriptSegment } from "./youtube";

export async function fetchTranscriptViaYoutubeTranscript(
  videoId: string,
  lang?: string
): Promise<TranscriptResponse> {
  try {
    const rawSegments = await YoutubeTranscript.fetchTranscript(videoId, {
      lang: lang && lang !== "default" ? lang : undefined,
    });

    if (!rawSegments || rawSegments.length === 0) {
      throw new Error("No transcript lines returned from youtube-transcript.");
    }

    const segments: TranscriptSegment[] = rawSegments.map((item, index) => {
      // offset is in seconds or milliseconds depending on format
      const startMs = item.offset < 100000 ? Math.round(item.offset * 1000) : Math.round(item.offset);
      const durMs = item.duration < 100000 ? Math.round(item.duration * 1000) : Math.round(item.duration);
      const endMs = startMs + durMs;

      return {
        text: decodeEntities(item.text.trim()),
        start_ms: startMs,
        end_ms: endMs,
        startFormatted: formatTimestamp(startMs),
        endFormatted: formatTimestamp(endMs),
      };
    });

    const fullText = segments.map((s) => s.text).join(" ");
    const durationSeconds = segments.length > 0 ? Math.ceil(segments[segments.length - 1].end_ms / 1000) : 0;

    return {
      metadata: {
        id: videoId,
        title: "YouTube Video",
        author: "YouTube Creator",
        durationSeconds,
        durationFormatted: formatTimestamp(durationSeconds * 1000),
        thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      },
      availableLanguages: [
        {
          id: lang || "en",
          languageCode: lang || "en",
          name: (lang || "en").toUpperCase(),
          isAutoGenerated: true,
        },
      ],
      selectedLanguage: lang || "en",
      segments,
      fullText,
    };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`YOUTUBE_TRANSCRIPT_ERROR: ${msg}`);
  }
}

