import { getCloudflareContext } from "@opennextjs/cloudflare";

export interface TranscriptSegment {
  start_ms: number;
  end_ms: number;
  startFormatted: string;
  endFormatted: string;
  text: string;
}

export interface TranscriptLanguage {
  id: string;
  languageCode: string;
  name: string;
  isAutoGenerated?: boolean;
}

export interface VideoMetadata {
  id: string;
  title: string;
  author: string;
  channelId?: string;
  durationSeconds: number;
  durationFormatted: string;
  thumbnail: string;
  viewCount?: string;
}

export interface TranscriptResponse {
  metadata: VideoMetadata;
  selectedLanguage: string;
  availableLanguages: TranscriptLanguage[];
  segments: TranscriptSegment[];
  fullText: string;
}

interface RawCaptionTrack {
  baseUrl: string;
  name?: {
    runs?: Array<{ text: string }>;
    simpleText?: string;
  };
  vssId?: string;
  languageCode: string;
  kind?: string;
  isTranslatable?: boolean;
}

const INNERTUBE_API_URL = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";
const INNERTUBE_CLIENT_VERSION = "20.10.38";

/**
 * Extracts YouTube video ID from various URL patterns or raw ID string.
 */
export function extractVideoId(input: string): string | null {
  if (!input || typeof input !== "string") return null;

  const trimmed = input.trim();

  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) {
    return trimmed;
  }

  const patterns = [
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/live\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/v\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?youtu\.be\/([a-zA-Z0-9_-]{11})/i,
  ];

  for (const pattern of patterns) {
    const match = trimmed.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  try {
    const url = new URL(trimmed.startsWith("http") ? trimmed : `https://${trimmed}`);
    const v = url.searchParams.get("v");
    if (v && /^[a-zA-Z0-9_-]{11}$/.test(v)) {
      return v;
    }
  } catch {
    // ignore
  }

  return null;
}

/**
 * Formats seconds or milliseconds cleanly as M:SS (e.g. 0:00, 1:00, 2:05) or H:MM:SS (e.g. 1:04:20)
 */
export function formatTimestamp(secondsOrMs: number, isMs = false): string {
  const totalSeconds = Math.max(0, Math.floor(isMs ? secondsOrMs / 1000 : secondsOrMs));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const pad = (num: number) => num.toString().padStart(2, "0");

  if (hours > 0) {
    return `${hours}:${pad(minutes)}:${pad(seconds)}`;
  }
  return `${minutes}:${pad(seconds)}`;
}

/**
 * Decodes common HTML entities in transcript XML text.
 */
export function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/\n/g, " ")
    .trim();
}

/**
 * Merges raw transcript fragments into clean, uniform 6-second time windows (0-6s, 6-12s, 12-18s, etc.).
 */
export function mergeSegments(
  rawSegments: TranscriptSegment[],
  windowDurationMs: number = 6000
): TranscriptSegment[] {
  if (!rawSegments || rawSegments.length === 0) return [];

  const merged: TranscriptSegment[] = [];
  let currentGroup: TranscriptSegment[] = [];
  let currentWindowStartMs = Math.floor(rawSegments[0].start_ms / windowDurationMs) * windowDurationMs;

  const flushGroup = () => {
    if (currentGroup.length === 0) return;

    const last = currentGroup[currentGroup.length - 1];
    const combinedText = currentGroup
      .map((s) => s.text.trim())
      .filter(Boolean)
      .join(" ");

    if (combinedText) {
      const windowEndMs = Math.max(last.end_ms, currentWindowStartMs + windowDurationMs);
      merged.push({
        start_ms: currentWindowStartMs,
        end_ms: windowEndMs,
        startFormatted: formatTimestamp(currentWindowStartMs, true),
        endFormatted: formatTimestamp(windowEndMs, true),
        text: combinedText,
      });
    }
    currentGroup = [];
  };

  for (let i = 0; i < rawSegments.length; i++) {
    const seg = rawSegments[i];
    const cleanText = seg.text.trim();
    if (!cleanText) continue;

    if (seg.start_ms >= currentWindowStartMs + windowDurationMs && currentGroup.length > 0) {
      flushGroup();
      currentWindowStartMs = Math.floor(seg.start_ms / windowDurationMs) * windowDurationMs;
    }

    currentGroup.push(seg);
  }

  flushGroup();
  return merged;
}

/**
 * Parses transcript XML from either srv3 (<p t="ms" d="ms">) or classic (<text start="s" dur="s">).
 */
function parseTranscriptXml(xml: string): TranscriptSegment[] {
  const rawSegments: TranscriptSegment[] = [];

  // 1. Try srv3 format (<p t="ms" d="ms">...<s>word</s>...</p>)
  const pRegex = /<p\s+t="(\d+)"(?:\s+d="(\d+)")?[^>]*>([\s\S]*?)<\/p>/g;
  let pMatch: RegExpExecArray | null;

  while ((pMatch = pRegex.exec(xml)) !== null) {
    const startMs = parseInt(pMatch[1], 10);
    const durMs = pMatch[2] ? parseInt(pMatch[2], 10) : 3000;
    const endMs = startMs + durMs;
    const inner = pMatch[3];

    let text = "";
    const sRegex = /<s[^>]*>([^<]*)<\/s>/g;
    let sMatch: RegExpExecArray | null;
    while ((sMatch = sRegex.exec(inner)) !== null) {
      text += sMatch[1];
    }
    if (!text) {
      text = inner.replace(/<[^>]+>/g, "");
    }

    text = decodeEntities(text);
    if (text) {
      rawSegments.push({
        start_ms: startMs,
        end_ms: endMs,
        startFormatted: formatTimestamp(startMs, true),
        endFormatted: formatTimestamp(endMs, true),
        text,
      });
    }
  }

  if (rawSegments.length > 0) {
    return mergeSegments(rawSegments, 6000);
  }

  // 2. Fallback to classic format: <text start="12.34" dur="4.56">content</text>
  const textRegex = /<text\s+start="([\d.]+)"(?:\s+dur="([\d.]+)")?[^>]*>([\s\S]*?)<\/text>/g;
  let tMatch: RegExpExecArray | null;

  while ((tMatch = textRegex.exec(xml)) !== null) {
    const startSec = parseFloat(tMatch[1]);
    const durSec = tMatch[2] ? parseFloat(tMatch[2]) : 3;
    const startMs = Math.round(startSec * 1000);
    const endMs = Math.round((startSec + durSec) * 1000);
    const text = decodeEntities(tMatch[3]);

    if (text) {
      rawSegments.push({
        start_ms: startMs,
        end_ms: endMs,
        startFormatted: formatTimestamp(startMs, true),
        endFormatted: formatTimestamp(endMs, true),
        text,
      });
    }
  }

  return mergeSegments(rawSegments, 6000);
}

/**
 * Helper to get YouTube Session Cookie from options, Cloudflare context, or default fallback
 */
function getEffectiveCookie(customCookie?: string): string {
  if (customCookie?.trim()) return customCookie.trim();

  try {
    const cf = getCloudflareContext();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const env = cf?.env as any;
    if (env?.YOUTUBE_COOKIE) {
      return env.YOUTUBE_COOKIE;
    }
  } catch {
    // ignore
  }

  return process.env.YOUTUBE_COOKIE || "VISITOR_INFO1_LIVE=jeCAn7bB8KM";
}

/**
 * Helper to get Scraper / Proxy Settings
 */
function getProxyConfig(): { scraperApiKey?: string; proxyUrl?: string } {
  try {
    const cf = getCloudflareContext();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const env = cf?.env as any;
    if (env?.SCRAPER_API_KEY || env?.PROXY_URL) {
      return {
        scraperApiKey: env.SCRAPER_API_KEY,
        proxyUrl: env.PROXY_URL,
      };
    }
  } catch {
    // ignore
  }
  return {
    scraperApiKey: process.env.SCRAPER_API_KEY,
    proxyUrl: process.env.PROXY_URL,
  };
}

const CLIENT_CONFIGS = [
  {
    name: "ANDROID",
    context: {
      client: {
        clientName: "ANDROID",
        clientVersion: INNERTUBE_CLIENT_VERSION,
        androidSdkVersion: 34,
        hl: "en",
        gl: "US",
      },
    },
    headers: {
      "Content-Type": "application/json",
      "User-Agent": `com.google.android.youtube/${INNERTUBE_CLIENT_VERSION} (Linux; U; Android 14)`,
      "X-YouTube-Client-Name": "3",
      "X-YouTube-Client-Version": INNERTUBE_CLIENT_VERSION,
      "Origin": "https://www.youtube.com",
    },
  },
  {
    name: "IOS",
    context: {
      client: {
        clientName: "IOS",
        clientVersion: INNERTUBE_CLIENT_VERSION,
        deviceModel: "iPhone16,2",
        osVersion: "18.1.0",
        hl: "en",
        gl: "US",
      },
    },
    headers: {
      "Content-Type": "application/json",
      "User-Agent": `com.google.ios.youtube/${INNERTUBE_CLIENT_VERSION} (iPhone16,2; U; CPU iOS 18_1_0 like Mac OS X; en_US)`,
      "X-YouTube-Client-Name": "5",
      "X-YouTube-Client-Version": INNERTUBE_CLIENT_VERSION,
      "Origin": "https://www.youtube.com",
    },
  },
];

/**
 * Fetch video metadata and transcript using Mobile InnerTube Player API directly.
 * Completely eliminates HTML watch-page scraping and prevents Cloudflare Worker IP CAPTCHAs.
 */
export async function getTranscript(
  videoId: string,
  options?: { lang?: string; cookie?: string }
): Promise<TranscriptResponse> {
  const effectiveCookie = getEffectiveCookie(options?.cookie);
  const { scraperApiKey, proxyUrl } = getProxyConfig();

  const viaProxy = (targetUrl: string, init?: RequestInit) => {
    if (scraperApiKey) {
      const url = `https://api.scraperapi.com/?api_key=${scraperApiKey}&url=${encodeURIComponent(targetUrl)}`;
      return fetch(url, init);
    }
    if (proxyUrl) {
      const url = proxyUrl.includes("{url}")
        ? proxyUrl.replace("{url}", encodeURIComponent(targetUrl))
        : `${proxyUrl}${encodeURIComponent(targetUrl)}`;
      return fetch(url, init);
    }
    return fetch(targetUrl, init);
  };

  let captionTracks: RawCaptionTrack[] = [];
  let title = "YouTube Video";
  let author = "YouTube Channel";
  let channelId = "";
  let durationSeconds = 0;
  let viewCount: string | undefined;
  let thumbnail = `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;

  // 1. Fetch Player Data via Mobile InnerTube Clients (Android / iOS)
  for (const clientConfig of CLIENT_CONFIGS) {
    try {
      const requestHeaders: Record<string, string> = {
        ...clientConfig.headers,
        Cookie: effectiveCookie,
      };

      const playerResp = await viaProxy(INNERTUBE_API_URL, {
        method: "POST",
        headers: requestHeaders,
        body: JSON.stringify({
          context: clientConfig.context,
          videoId,
        }),
      });

      if (playerResp.ok) {
        const data = (await playerResp.json()) as {
          videoDetails?: {
            title?: string;
            author?: string;
            channelId?: string;
            lengthSeconds?: string;
            viewCount?: string;
            thumbnail?: { thumbnails?: Array<{ url: string }> };
          };
          captions?: {
            playerCaptionsTracklistRenderer?: {
              captionTracks?: RawCaptionTrack[];
            };
          };
          playabilityStatus?: {
            status?: string;
            reason?: string;
          };
        };

        if (data.playabilityStatus?.status === "UNPLAYABLE") {
          throw new Error(
            `PRIVATE_VIDEO: ${data.playabilityStatus.reason || "This video is unavailable or restricted."}`
          );
        }

        const details = data.videoDetails;
        if (details) {
          if (details.title) title = details.title;
          if (details.author) author = details.author;
          if (details.channelId) channelId = details.channelId;
          if (details.lengthSeconds) durationSeconds = parseInt(details.lengthSeconds, 10);
          if (details.viewCount) viewCount = Number(details.viewCount).toLocaleString();
          if (details.thumbnail?.thumbnails?.length) {
            thumbnail = details.thumbnail.thumbnails.slice(-1)[0].url;
          }
        }

        const tracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
        if (tracks.length > 0) {
          captionTracks = tracks;
          break; // successfully retrieved tracks!
        }
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.startsWith("PRIVATE_VIDEO:")) {
        throw err;
      }
    }
  }

  // 2. Fallback to YouTube oEmbed if title is still missing
  if (title === "YouTube Video") {
    try {
      const oembedRes = await fetch(
        `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`,
        { headers: { "User-Agent": "Mozilla/5.0" } }
      );
      if (oembedRes.ok) {
        const oembedData = (await oembedRes.json()) as { title?: string; author_name?: string };
        if (oembedData?.title) title = oembedData.title;
        if (oembedData?.author_name) author = oembedData.author_name;
      }
    } catch {
      // ignore
    }
  }

  if (captionTracks.length === 0) {
    throw new Error(
      "NO_TRANSCRIPT: No captions or transcripts are available for this video on YouTube."
    );
  }

  // 3. Map available languages
  const availableLanguages: TranscriptLanguage[] = captionTracks.map((t, idx) => {
    const name = t.name?.runs?.[0]?.text || t.name?.simpleText || t.languageCode;
    const isAuto = t.kind === "asr" || t.vssId?.startsWith("a.") || false;
    const uniqueId = t.vssId || `${t.languageCode}-${isAuto ? "auto" : "manual"}-${idx}`;
    return {
      id: uniqueId,
      languageCode: t.languageCode,
      name,
      isAutoGenerated: isAuto,
    };
  });

  // 4. Select requested language or default to English/native audio track
  let selectedTrack: RawCaptionTrack;
  if (options?.lang && options.lang !== "default") {
    selectedTrack =
      captionTracks.find((t, idx) => {
        const uniqueId = t.vssId || `${t.languageCode}-${t.kind === "asr" ? "auto" : "manual"}-${idx}`;
        return uniqueId === options.lang || t.languageCode === options.lang;
      }) || captionTracks[0];
  } else {
    selectedTrack =
      captionTracks.find((t) => (t.languageCode === "en" || t.languageCode?.startsWith("en")) && t.kind !== "asr") ||
      captionTracks.find((t) => t.languageCode === "en" || t.languageCode?.startsWith("en")) ||
      captionTracks[0];
  }

  const selectedTrackIdx = captionTracks.indexOf(selectedTrack);
  const selectedLanguage =
    selectedTrack.vssId ||
    `${selectedTrack.languageCode}-${selectedTrack.kind === "asr" ? "auto" : "manual"}-${selectedTrackIdx >= 0 ? selectedTrackIdx : 0}`;

  // 5. Download transcript XML with mobile User-Agent
  const transcriptResp = await viaProxy(selectedTrack.baseUrl, {
    headers: {
      "User-Agent": `com.google.android.youtube/${INNERTUBE_CLIENT_VERSION} (Linux; U; Android 14)`,
      Cookie: effectiveCookie,
    },
  });

  if (!transcriptResp.ok) {
    throw new Error("NO_TRANSCRIPT: Could not download the transcript track from YouTube.");
  }

  const xml = await transcriptResp.text();
  const segments = parseTranscriptXml(xml);

  if (segments.length === 0) {
    throw new Error("NO_TRANSCRIPT: No transcript text segments found for this video.");
  }

  const fullText = segments.map((s) => s.text).join(" ");

  if (durationSeconds === 0 && segments.length > 0) {
    durationSeconds = Math.ceil(segments[segments.length - 1].end_ms / 1000);
  }

  const metadata: VideoMetadata = {
    id: videoId,
    title,
    author,
    channelId,
    durationSeconds,
    durationFormatted: formatTimestamp(durationSeconds, false),
    thumbnail,
    viewCount,
  };

  return {
    metadata,
    selectedLanguage,
    availableLanguages,
    segments,
    fullText,
  };
}
