import { Innertube } from "youtubei.js";

export interface TranscriptSegment {
  start_ms: number;
  end_ms: number;
  startFormatted: string;
  endFormatted: string;
  text: string;
}

export interface TranscriptLanguage {
  languageCode: string;
  name: string;
  isAutoGenerated?: boolean;
}

export interface VideoMetadata {
  id: string;
  title: string;
  author: string;
  channelId?: string;
  durationSeconds: number;
  durationFormatted: string;
  thumbnail: string;
  viewCount?: string;
}

export interface TranscriptResponse {
  metadata: VideoMetadata;
  selectedLanguage: string;
  availableLanguages: TranscriptLanguage[];
  segments: TranscriptSegment[];
  fullText: string;
}

/**
 * Extracts YouTube video ID from various URL patterns or raw ID string.
 */
export function extractVideoId(input: string): string | null {
  if (!input || typeof input !== "string") return null;

  const trimmed = input.trim();

  // If input is already an 11-character YouTube video ID
  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) {
    return trimmed;
  }

  // Common YouTube URL regex patterns
  const patterns = [
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/live\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/v\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?youtu\.be\/([a-zA-Z0-9_-]{11})/i,
  ];

  for (const pattern of patterns) {
    const match = trimmed.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  // Query parameter fallback
  try {
    const url = new URL(trimmed.startsWith("http") ? trimmed : `https://${trimmed}`);
    const v = url.searchParams.get("v");
    if (v && /^[a-zA-Z0-9_-]{11}$/.test(v)) {
      return v;
    }
  } catch {
    // Not a standard URL
  }

  return null;
}

/**
 * Formats seconds or milliseconds into HH:MM:SS or MM:SS
 */
export function formatTimestamp(secondsOrMs: number, isMs = false): string {
  const totalSeconds = Math.max(0, Math.floor(isMs ? secondsOrMs / 1000 : secondsOrMs));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const pad = (num: number) => num.toString().padStart(2, "0");

  if (hours > 0) {
    return `${hours}:${pad(minutes)}:${pad(seconds)}`;
  }
  return `${pad(minutes)}:${pad(seconds)}`;
}

// Global cached Innertube instance
let ytInstance: Innertube | null = null;

async function getInnertube(cookie?: string): Promise<Innertube> {
  if (cookie) {
    // If custom cookie is provided, create a separate authenticated instance
    return await Innertube.create({
      cookie: cookie,
      fetch: globalThis.fetch,
    });
  }

  if (!ytInstance) {
    ytInstance = await Innertube.create({
      fetch: globalThis.fetch,
    });
  }
  return ytInstance;
}

/**
 * Fetch video metadata and transcript.
 */
export async function fetchYouTubeTranscript(
  videoId: string,
  options?: { lang?: string; cookie?: string }
): Promise<TranscriptResponse> {
  const yt = await getInnertube(options?.cookie);

  // 1. Fetch video basic info & metadata
  const info = await yt.getInfo(videoId);
  const basicInfo = info.basic_info;

  const durationSeconds = Number(basicInfo.duration || 0);
  const bestThumbnail =
    basicInfo.thumbnail?.slice(-1)[0]?.url ||
    `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;

  const metadata: VideoMetadata = {
    id: videoId,
    title: basicInfo.title || "Untitled Video",
    author: basicInfo.author || "Unknown Channel",
    channelId: basicInfo.channel_id,
    durationSeconds: durationSeconds,
    durationFormatted: formatTimestamp(durationSeconds),
    thumbnail: bestThumbnail,
    viewCount: basicInfo.view_count?.toLocaleString(),
  };

  // 2. Fetch transcript
  let transcriptData;
  try {
    transcriptData = await info.getTranscript();
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    if (
      errorMsg.includes("Transcript is disabled") ||
      errorMsg.includes("No transcripts available") ||
      errorMsg.includes("Transcript not available")
    ) {
      throw new Error(
        "NO_TRANSCRIPT: এই ভিডিওটিতে কোনো ট্রান্সক্রিপ্ট বা সাবটাইটেল উপলব্ধ নেই। (No transcripts or captions are available for this video on YouTube)."
      );
    }
    if (
      errorMsg.includes("Private video") ||
      errorMsg.includes("Sign in") ||
      errorMsg.includes("age")
    ) {
      throw new Error(
        "PRIVATE_VIDEO: এটি একটি প্রাইভেট বা বয়স-সীমাবদ্ধ ভিডিও। (This is a private or restricted video requiring authentication)."
      );
    }
    throw new Error(`TRANSCRIPT_ERROR: ${errorMsg}`);
  }

  if (!transcriptData) {
    throw new Error(
      "NO_TRANSCRIPT: এই ভিডিওটিতে কোনো ট্রান্সক্রিপ্ট বা সাবটাইটেল পাওয়া যায়নি। (No transcript tracks found for this video)."
    );
  }

  // 3. Extract available languages
  const availableLanguages: TranscriptLanguage[] = [];
  if (transcriptData.languages && Array.isArray(transcriptData.languages)) {
    for (const lang of transcriptData.languages) {
      if (typeof lang === "string") {
        availableLanguages.push({
          languageCode: lang,
          name: lang,
        });
      } else if (lang && typeof lang === "object") {
        const anyLang = lang as Record<string, unknown>;
        const code = String(anyLang.language_code || anyLang.code || anyLang.language || "");
        const name = String(anyLang.name || anyLang.language_name || code);
        if (code) {
          availableLanguages.push({
            languageCode: code,
            name: name,
            isAutoGenerated: Boolean(anyLang.is_auto_generated || anyLang.isAutoGenerated),
          });
        }
      }
    }
  }

  // If user requested a specific language, switch track
  let selectedLanguage = "default";
  if (options?.lang && options.lang !== "default") {
    try {
      await transcriptData.selectLanguage(options.lang);
      selectedLanguage = options.lang;
    } catch {
      // Keep default if selection fails
    }
  }

  // 4. Extract and parse transcript segments
  // TranscriptInfo structure has transcript.content.body.initial_segments or segments
  const rawSegments =
    (transcriptData as unknown as {
      transcript?: {
        content?: {
          body?: {
            initial_segments?: Array<Record<string, unknown>>;
          };
        };
        segments?: Array<Record<string, unknown>>;
      };
    })?.transcript?.content?.body?.initial_segments ||
    (transcriptData as unknown as { transcript?: { segments?: Array<Record<string, unknown>> } })
      ?.transcript?.segments ||
    [];

  const segments: TranscriptSegment[] = [];

  for (const seg of rawSegments) {
    let text = "";
    if (typeof seg.text === "string") {
      text = seg.text;
    } else if (seg.snippet && typeof (seg.snippet as Record<string, unknown>).text === "string") {
      text = String((seg.snippet as Record<string, unknown>).text);
    } else if (seg.text && typeof (seg.text as Record<string, unknown>).toString === "function") {
      text = (seg.text as Record<string, unknown>).toString();
    }

    // Clean whitespace
    text = text.replace(/\n/g, " ").trim();
    if (!text) continue;

    const start_ms = Number(seg.start_ms || seg.start_time_ms || (Number(seg.start || 0) * 1000) || 0);
    const end_ms = Number(seg.end_ms || seg.end_time_ms || (Number(seg.end || 0) * 1000) || (start_ms + 3000));

    segments.push({
      start_ms,
      end_ms,
      startFormatted: formatTimestamp(start_ms, true),
      endFormatted: formatTimestamp(end_ms, true),
      text,
    });
  }

  if (segments.length === 0) {
    throw new Error(
      "NO_TRANSCRIPT: ভিডিওটিতে কোনো ট্রান্সক্রিপ্ট টেক্সট পাওয়া যায়নি। (No transcript text segments found)."
    );
  }

  const fullText = segments.map((s) => s.text).join(" ");

  return {
    metadata,
    selectedLanguage,
    availableLanguages,
    segments,
    fullText,
  };
}

