export interface TranscriptSegment {
  start_ms: number;
  end_ms: number;
  startFormatted: string;
  endFormatted: string;
  text: string;
}

export interface TranscriptLanguage {
  id: string;
  languageCode: string;
  name: string;
  isAutoGenerated?: boolean;
}

export interface VideoMetadata {
  id: string;
  title: string;
  author: string;
  channelId?: string;
  durationSeconds: number;
  durationFormatted: string;
  thumbnail: string;
  viewCount?: string;
}

export interface TranscriptResponse {
  metadata: VideoMetadata;
  selectedLanguage: string;
  availableLanguages: TranscriptLanguage[];
  segments: TranscriptSegment[];
  fullText: string;
}

interface RawCaptionTrack {
  baseUrl: string;
  name?: {
    runs?: Array<{ text: string }>;
    simpleText?: string;
  };
  vssId?: string;
  languageCode: string;
  kind?: string;
  isTranslatable?: boolean;
}

const INNERTUBE_API_URL = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";
const INNERTUBE_CLIENT_VERSION = "20.10.38";
const INNERTUBE_CONTEXT = {
  client: {
    clientName: "ANDROID",
    clientVersion: INNERTUBE_CLIENT_VERSION,
  },
};
const INNERTUBE_USER_AGENT = `com.google.android.youtube/${INNERTUBE_CLIENT_VERSION} (Linux; U; Android 14)`;
const WEB_USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/**
 * Extracts YouTube video ID from various URL patterns or raw ID string.
 */
export function extractVideoId(input: string): string | null {
  if (!input || typeof input !== "string") return null;

  const trimmed = input.trim();

  // If input is already an 11-character YouTube video ID
  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) {
    return trimmed;
  }

  // Common YouTube URL regex patterns
  const patterns = [
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/live\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?(?:www\.|m\.)?youtube\.com\/v\/([a-zA-Z0-9_-]{11})/i,
    /(?:https?:\/\/)?youtu\.be\/([a-zA-Z0-9_-]{11})/i,
  ];

  for (const pattern of patterns) {
    const match = trimmed.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  // Query parameter fallback
  try {
    const url = new URL(trimmed.startsWith("http") ? trimmed : `https://${trimmed}`);
    const v = url.searchParams.get("v");
    if (v && /^[a-zA-Z0-9_-]{11}$/.test(v)) {
      return v;
    }
  } catch {
    // Not a standard URL
  }

  return null;
}

/**
 * Formats seconds or milliseconds into HH:MM:SS or MM:SS
 */
export function formatTimestamp(secondsOrMs: number, isMs = false): string {
  const totalSeconds = Math.max(0, Math.floor(isMs ? secondsOrMs / 1000 : secondsOrMs));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const pad = (num: number) => num.toString().padStart(2, "0");

  if (hours > 0) {
    return `${hours}:${pad(minutes)}:${pad(seconds)}`;
  }
  return `${pad(minutes)}:${pad(seconds)}`;
}

/**
 * Decodes common HTML entities in transcript XML text.
 */
export function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/\n/g, " ")
    .trim();
}

/**
 * Parses transcript XML from either srv3 (<p t="ms" d="ms">) or classic (<text start="s" dur="s">).
 */
function parseTranscriptXml(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];

  // Try srv3 format (<p t="ms" d="ms">...<s>word</s>...</p>)
  const pRegex = /<p\s+t="(\d+)"(?:\s+d="(\d+)")?[^>]*>([\s\S]*?)<\/p>/g;
  let pMatch: RegExpExecArray | null;

  while ((pMatch = pRegex.exec(xml)) !== null) {
    const startMs = parseInt(pMatch[1], 10);
    const durMs = pMatch[2] ? parseInt(pMatch[2], 10) : 3000;
    const endMs = startMs + durMs;
    const inner = pMatch[3];

    let text = "";
    const sRegex = /<s[^>]*>([^<]*)<\/s>/g;
    let sMatch: RegExpExecArray | null;
    while ((sMatch = sRegex.exec(inner)) !== null) {
      text += sMatch[1];
    }
    if (!text) {
      text = inner.replace(/<[^>]+>/g, "");
    }

    text = decodeEntities(text);
    if (text) {
      segments.push({
        start_ms: startMs,
        end_ms: endMs,
        startFormatted: formatTimestamp(startMs, true),
        endFormatted: formatTimestamp(endMs, true),
        text,
      });
    }
  }

  if (segments.length > 0) {
    return segments;
  }

  // Fallback to classic format: <text start="12.34" dur="4.56">content</text>
  const textRegex = /<text\s+start="([\d.]+)"(?:\s+dur="([\d.]+)")?[^>]*>([\s\S]*?)<\/text>/g;
  let tMatch: RegExpExecArray | null;

  while ((tMatch = textRegex.exec(xml)) !== null) {
    const startSec = parseFloat(tMatch[1]);
    const durSec = tMatch[2] ? parseFloat(tMatch[2]) : 3;
    const startMs = Math.round(startSec * 1000);
    const endMs = Math.round((startSec + durSec) * 1000);
    const text = decodeEntities(tMatch[3]);

    if (text) {
      segments.push({
        start_ms: startMs,
        end_ms: endMs,
        startFormatted: formatTimestamp(startMs, true),
        endFormatted: formatTimestamp(endMs, true),
        text,
      });
    }
  }

  return segments;
}

/**
 * Fetch video metadata and transcript for a YouTube video.
 */
export async function fetchYouTubeTranscript(
  videoId: string,
  options?: { lang?: string; cookie?: string }
): Promise<TranscriptResponse> {
  const customHeaders: Record<string, string> = {
    "Content-Type": "application/json",
    "User-Agent": INNERTUBE_USER_AGENT,
  };

  if (options?.cookie) {
    customHeaders["Cookie"] = options.cookie;
  }

  // 1. Fetch player data via InnerTube Android client
  let captionTracks: RawCaptionTrack[] = [];
  let title = "YouTube Video";
  let author = "YouTube Channel";
  let channelId = "";
  let durationSeconds = 0;
  let viewCount: string | undefined;
  let thumbnail = `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;

  try {
    const playerResp = await fetch(INNERTUBE_API_URL, {
      method: "POST",
      headers: customHeaders,
      body: JSON.stringify({
        context: INNERTUBE_CONTEXT,
        videoId,
      }),
    });

    if (playerResp.ok) {
      const data = (await playerResp.json()) as {
        videoDetails?: {
          title?: string;
          author?: string;
          channelId?: string;
          lengthSeconds?: string;
          viewCount?: string;
          thumbnail?: { thumbnails?: Array<{ url: string }> };
        };
        captions?: {
          playerCaptionsTracklistRenderer?: {
            captionTracks?: RawCaptionTrack[];
          };
        };
        playabilityStatus?: {
          status?: string;
          reason?: string;
        };
      };

      if (data.playabilityStatus?.status === "UNPLAYABLE") {
        throw new Error(
          `PRIVATE_VIDEO: ${data.playabilityStatus.reason || "This video is unavailable or restricted."}`
        );
      }

      const details = data.videoDetails;
      if (details) {
        title = details.title || title;
        author = details.author || author;
        channelId = details.channelId || "";
        durationSeconds = parseInt(details.lengthSeconds || "0", 10);
        viewCount = details.viewCount ? Number(details.viewCount).toLocaleString() : undefined;
        if (details.thumbnail?.thumbnails?.length) {
          thumbnail = details.thumbnail.thumbnails.slice(-1)[0].url;
        }
      }

      captionTracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.startsWith("PRIVATE_VIDEO:")) {
      throw err;
    }
  }

  // 2. Fallback to web page scraping if no caption tracks found via InnerTube
  if (captionTracks.length === 0) {
    try {
      const pageResp = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
        headers: {
          "User-Agent": WEB_USER_AGENT,
          ...(options?.cookie ? { Cookie: options.cookie } : {}),
        },
      });

      if (pageResp.ok) {
        const html = await pageResp.text();

        // Extract title from HTML if not present
        if (title === "YouTube Video") {
          const titleMatch = html.match(/<title>([^<]*)<\/title>/);
          if (titleMatch && titleMatch[1]) {
            title = titleMatch[1].replace(" - YouTube", "").trim();
          }
        }

        // Search for captionTracks inside ytInitialPlayerResponse
        const match = html.match(/"captionTracks":\s*(\[[^\]]+\])/);
        if (match && match[1]) {
          try {
            captionTracks = JSON.parse(match[1]) as RawCaptionTrack[];
          } catch {
            // parsing failed
          }
        }
      }
    } catch {
      // Fallback failed
    }
  }

  if (captionTracks.length === 0) {
    throw new Error(
      "NO_TRANSCRIPT: No captions or transcripts are available for this video on YouTube."
    );
  }

  // 3. Prepare available languages list with unique IDs
  const availableLanguages: TranscriptLanguage[] = captionTracks.map((t, idx) => {
    const name = t.name?.runs?.[0]?.text || t.name?.simpleText || t.languageCode;
    const isAuto = t.kind === "asr" || t.vssId?.startsWith("a.") || false;
    const uniqueId = t.vssId || `${t.languageCode}-${isAuto ? "auto" : "manual"}-${idx}`;
    return {
      id: uniqueId,
      languageCode: t.languageCode,
      name,
      isAutoGenerated: isAuto,
    };
  });

  // 4. Select requested language or default to English or first track
  let selectedTrack: RawCaptionTrack;
  if (options?.lang && options.lang !== "default") {
    selectedTrack =
      captionTracks.find((t, idx) => {
        const uniqueId = t.vssId || `${t.languageCode}-${t.kind === "asr" ? "auto" : "manual"}-${idx}`;
        return uniqueId === options.lang || t.languageCode === options.lang;
      }) || captionTracks[0];
  } else {
    // Prefer manual English if available, then auto English, otherwise first track
    selectedTrack =
      captionTracks.find((t) => t.languageCode === "en" && t.kind !== "asr") ||
      captionTracks.find((t) => t.languageCode === "en") ||
      captionTracks[0];
  }

  const selectedTrackIdx = captionTracks.indexOf(selectedTrack);
  const selectedLanguage =
    selectedTrack.vssId ||
    `${selectedTrack.languageCode}-${selectedTrack.kind === "asr" ? "auto" : "manual"}-${selectedTrackIdx >= 0 ? selectedTrackIdx : 0}`;

  // 5. Fetch transcript XML
  const transcriptResp = await fetch(selectedTrack.baseUrl, {
    headers: {
      "User-Agent": WEB_USER_AGENT,
    },
  });

  if (!transcriptResp.ok) {
    throw new Error("NO_TRANSCRIPT: Could not download the transcript track from YouTube.");
  }

  const xml = await transcriptResp.text();
  const segments = parseTranscriptXml(xml);

  if (segments.length === 0) {
    throw new Error("NO_TRANSCRIPT: No transcript text segments found for this video.");
  }

  const fullText = segments.map((s) => s.text).join(" ");

  const metadata: VideoMetadata = {
    id: videoId,
    title,
    author,
    channelId,
    durationSeconds,
    durationFormatted: formatTimestamp(durationSeconds),
    thumbnail,
    viewCount,
  };

  return {
    metadata,
    selectedLanguage,
    availableLanguages,
    segments,
    fullText,
  };
}
